export type DraftPriceTier = {
  label: string;
  minimum_price: number;
  maximum_price: number;
};

export type DraftProductSeed = {
  id: string;
  code: string;
  name: string;
  slug: string;
  item_type: "service";
  service_group: string;
  category_ids: string[];
  short_description: string;
  description: string;
  thumbnail_url: string;
  banner_url: string;
  image_urls: string[];
  service_highlights?: string[];
  included_items?: string[];
  ideal_for?: string[];
  pricing_notes?: string[];
  faq?: Array<{
    question: string;
    answer: string;
  }>;
  terms_and_conditions?: string[];
  availability_note?: string;
  pricing_model: string;
  price_tiers: {
    low: DraftPriceTier;
    medium: DraftPriceTier;
    high: DraftPriceTier;
  };
  quotation_config: {
    quotation_enabled: boolean;
    quantity_required: boolean;
    duration_required: boolean;
    manual_review_required: boolean;
    quantity_label?: string;
    quantity_unit?: string;
    minimum_quantity?: number;
    duration_label?: string;
    duration_unit?: string;
    minimum_duration?: number;
  };
  search_tags: string[];
  search_text: string;
  sort_order: number;
  is_featured: boolean;
  is_active: boolean;
};

const defaultTerms = [
  "Final quotation depends on event size, service scope, and site requirements.",
  "Transport, labour, and setup timing are confirmed during quotation review.",
];

export const defaultProductThumbnailUrl =
  "https://firebasestorage.googleapis.com/v0/b/ecostory-b31b6.firebasestorage.app/o/wedding%2Ftent_image.png?alt=media&token=8e7f7cee-c373-4cfa-aba2-448a863afeda";

export const defaultProductBannerUrl =
  "https://firebasestorage.googleapis.com/v0/b/ecostory-b31b6.firebasestorage.app/o/wedding%2Ftent3.png?alt=media&token=9ebe5f82-41a7-4ae5-844b-eddf6d26ede5";

export const defaultProductImageUrls = [
  "https://firebasestorage.googleapis.com/v0/b/ecostory-b31b6.firebasestorage.app/o/wedding%2Ftent_image.png?alt=media&token=8e7f7cee-c373-4cfa-aba2-448a863afeda",
  "https://firebasestorage.googleapis.com/v0/b/ecostory-b31b6.firebasestorage.app/o/wedding%2Ftent3.png?alt=media&token=9ebe5f82-41a7-4ae5-844b-eddf6d26ede5",
  "https://firebasestorage.googleapis.com/v0/b/ecostory-b31b6.firebasestorage.app/o/wedding%2Ftent2.png?alt=media&token=125cae6b-7890-4b03-ac51-2eb53113d076",
  "https://firebasestorage.googleapis.com/v0/b/ecostory-b31b6.firebasestorage.app/o/wedding%2Ftent1.png?alt=media&token=7a424ea4-0ff7-4539-bb05-26e106d6e8a3",
];

function makeSearchText(tags: string[], description: string) {
  return `${tags.join(" ")} ${description}`.toLowerCase();
}

function makePriceTiers() {
  return {
    low: { label: "Basic", minimum_price: 1, maximum_price: 1 },
    medium: { label: "Standard", minimum_price: 3, maximum_price: 3 },
    high: { label: "Premium", minimum_price: 5, maximum_price: 5 },
  };
}

function makeFeatured(code: string) {
  return [
    "TS-01",
    "SF-01",
    "ST-03",
    "CT-03",
    "EN-05",
    "PH-01",
    "BR-05",
    "EM-02",
  ].includes(code);
}

function buildProduct(
  sortOrder: number,
  seed: Omit<DraftProductSeed, "item_type" | "thumbnail_url" | "banner_url" | "image_urls" | "price_tiers" | "search_text" | "sort_order" | "is_featured" | "is_active" | "terms_and_conditions"> & {
    banner_url?: string;
    search_tags: string[];
  }
): DraftProductSeed {
  return {
    ...seed,
    item_type: "service",
    thumbnail_url: defaultProductThumbnailUrl,
    banner_url: seed.banner_url ?? defaultProductBannerUrl,
    image_urls: defaultProductImageUrls,
    price_tiers: makePriceTiers(),
    search_text: makeSearchText(seed.search_tags, seed.short_description),
    sort_order: sortOrder,
    is_featured: makeFeatured(seed.code),
    is_active: true,
    terms_and_conditions: defaultTerms,
  };
}

export const draftProductSeedData: DraftProductSeed[] = [
  buildProduct(1, {
    id: "tent-shamiana",
    code: "TS-01",
    name: "Tent / Shamiana",
    slug: "tent-shamiana",
    service_group: "tent-and-structure",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Tent and shamiana setup for weddings, family events, corporate functions, and religious ceremonies.",
    description: "Tent and shamiana arrangements for covered event spaces, guest hosting, and function setups across celebration types.",
    pricing_model: "per_sq_ft",
    banner_url: "",
    service_highlights: ["Covered structure setup", "Suitable for indoor-outdoor functions", "Scales with event area"],
    included_items: ["Tent fabric and structure setup", "Basic installation", "Dismantling after event"],
    ideal_for: ["Wedding functions", "Community events", "Religious ceremonies"],
    pricing_notes: ["Customer pricing to be finalized by operations team.", "Keep internal costing separate from customer quotation."],
    availability_note: "Recommended to confirm area size before generating a quotation.",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Tent area",
      quantity_unit: "sq_ft",
      minimum_quantity: 100,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["tent", "shamiana", "pandal", "wedding tent", "event tent", "tent rental"],
  }),
  buildProduct(2, {
    id: "canopy-pandal",
    code: "TS-02",
    name: "Canopy / Pandal",
    slug: "canopy-pandal",
    service_group: "tent-and-structure",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Canopy and pandal setup for covered event arrangements.",
    description: "Flexible canopy and pandal structure support for ceremonies, seating areas, and weather-protected hosting zones.",
    pricing_model: "per_sq_ft",
    banner_url: "",
    service_highlights: ["Covered hosting area", "Custom setup by site", "Useful for open grounds and home events"],
    included_items: ["Canopy structure", "Basic setup support", "Removal after function"],
    ideal_for: ["Haldi and mehendi", "Birthday events", "Religious gatherings"],
    pricing_notes: ["Customer price needs confirmation from team."],
    availability_note: "Best quoted after understanding site dimensions.",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Covered area",
      quantity_unit: "sq_ft",
      minimum_quantity: 100,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["canopy", "pandal", "event canopy", "wedding pandal", "pandal setup"],
  }),
  buildProduct(3, {
    id: "german-hangar-waterproof-cover",
    code: "TS-03",
    name: "German Hangar / Waterproof Cover",
    slug: "german-hangar-waterproof-cover",
    service_group: "tent-and-structure",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Large-format waterproof structure cover for premium and weather-safe events.",
    description: "Premium waterproof structural cover for larger-scale events needing stronger weather protection and cleaner presentation.",
    pricing_model: "per_sq_ft",
    banner_url: "",
    service_highlights: ["Premium event cover", "Weather-resistant structure", "Suitable for large event footprint"],
    included_items: ["Waterproof cover system", "Installation and removal"],
    ideal_for: ["Reception events", "Corporate functions", "Outdoor celebrations"],
    pricing_notes: ["Requires manual quotation based on area, site, and event duration."],
    availability_note: "Availability should be checked in advance for large dates.",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Covered area",
      quantity_unit: "sq_ft",
      minimum_quantity: 200,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["german hangar", "waterproof tent", "waterproof cover", "premium tent", "large event tent"],
  }),
  buildProduct(4, {
    id: "banquet-chairs",
    code: "SF-01",
    name: "Banquet Chairs",
    slug: "banquet-chairs",
    service_group: "chairs-and-seating",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Premium banquet seating for event guest arrangements.",
    description: "Banquet chair rental for weddings, receptions, social gatherings, and formal events.",
    pricing_model: "per_unit_per_day",
    banner_url: "",
    service_highlights: ["Guest seating support", "Suitable for formal events", "Day-wise rental"],
    included_items: ["Chair delivery", "Basic placement support", "Pickup after event"],
    ideal_for: ["Reception seating", "Corporate seating", "Prayer meets"],
    pricing_notes: ["Price depends on quantity and chair finish."],
    availability_note: "Large volume orders should be booked early.",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of chairs",
      quantity_unit: "chair",
      minimum_quantity: 20,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["banquet chair", "event chair", "chair rental", "wedding chair", "guest seating"],
  }),
  buildProduct(5, {
    id: "plastic-chairs",
    code: "SF-02",
    name: "Plastic Chairs",
    slug: "plastic-chairs",
    service_group: "chairs-and-seating",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Affordable plastic seating for practical event setups.",
    description: "Plastic chair rental for utility seating, casual events, and large guest count requirements.",
    pricing_model: "per_unit_per_day",
    banner_url: "",
    pricing_notes: ["Useful for high-volume seating requirements."],
    availability_note: "Best suited for practical utility seating.",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of chairs",
      quantity_unit: "chair",
      minimum_quantity: 20,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["plastic chair", "chair rental", "party chair", "function chair"],
  }),
  buildProduct(6, {
    id: "steel-chairs",
    code: "SF-03",
    name: "Steel Chairs",
    slug: "steel-chairs",
    service_group: "chairs-and-seating",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Durable steel seating for functions and public gatherings.",
    description: "Steel chair rental for practical guest seating, camps, and high-usage events.",
    pricing_model: "per_unit_per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of chairs",
      quantity_unit: "chair",
      minimum_quantity: 20,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["steel chair", "chair rental", "event chair", "public seating"],
  }),
  buildProduct(7, {
    id: "cushion-chairs",
    code: "SF-04",
    name: "Cushion Chairs",
    slug: "cushion-chairs",
    service_group: "chairs-and-seating",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Comfortable cushioned seating for guests and premium setups.",
    description: "Cushioned chair rental for premium event comfort and elevated seating presentation.",
    pricing_model: "per_unit_per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of chairs",
      quantity_unit: "chair",
      minimum_quantity: 20,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["cushion chair", "premium chair", "wedding seating", "event chair"],
  }),
  buildProduct(8, {
    id: "sofas-lounge-seating",
    code: "SF-05",
    name: "Sofas / Lounge Seating",
    slug: "sofas-lounge-seating",
    service_group: "chairs-and-seating",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Sofa and lounge seating for stage, VIP, and hospitality areas.",
    description: "Lounge seating rental for stage presentation, bridal areas, and guest comfort zones.",
    pricing_model: "per_unit_per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of sofa units",
      quantity_unit: "unit",
      minimum_quantity: 1,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["sofa rental", "lounge seating", "vip seating", "stage sofa"],
  }),
  buildProduct(9, {
    id: "tables",
    code: "SF-06",
    name: "Tables",
    slug: "tables",
    service_group: "tables-and-dining",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Dining, buffet, and side tables for event layouts.",
    description: "Tables for dining service, buffet counters, guest utility, and event support zones.",
    pricing_model: "per_unit_per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of tables",
      quantity_unit: "table",
      minimum_quantity: 1,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["table rental", "dining table", "buffet table", "event table"],
  }),
  buildProduct(10, {
    id: "temporary-beds-mattresses-bedding",
    code: "SF-07",
    name: "Temporary Beds / Mattresses / Bedding",
    slug: "temporary-beds-mattresses-bedding",
    service_group: "guest-stay-setup",
    category_ids: ["wedding-functions", "religious-domestic-ceremonies"],
    short_description: "Temporary sleeping arrangements for guest stay requirements.",
    description: "Guest stay support with temporary beds, mattresses, and bedding for residential and multi-day functions.",
    pricing_model: "per_unit_per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of bedding sets",
      quantity_unit: "set",
      minimum_quantity: 1,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["temporary bed", "mattress rental", "guest stay", "bedding rental"],
  }),
  buildProduct(11, {
    id: "carpets-floor-covering",
    code: "FC-01",
    name: "Carpets / Floor Covering",
    slug: "carpets-floor-covering",
    service_group: "flooring-and-covering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Carpet and floor covering for event areas and pathways.",
    description: "Floor covering setup for pathways, seating areas, stages, and guest movement zones.",
    pricing_model: "per_sq_ft",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Covered area",
      quantity_unit: "sq_ft",
      minimum_quantity: 50,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["carpet rental", "floor covering", "event carpet", "aisle carpet"],
  }),
  buildProduct(12, {
    id: "matting-green-turf",
    code: "FC-02",
    name: "Matting / Green Turf",
    slug: "matting-green-turf",
    service_group: "flooring-and-covering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Matting and green turf coverage for outdoor event spaces.",
    description: "Outdoor floor treatment with matting or turf for garden functions and open-ground hosting.",
    pricing_model: "per_sq_ft",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Covered area",
      quantity_unit: "sq_ft",
      minimum_quantity: 50,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["green turf", "event turf", "matting", "floor matting", "outdoor flooring"],
  }),
  buildProduct(13, {
    id: "stage-structure-raised-platform",
    code: "ST-01",
    name: "Stage Structure / Raised Platform",
    slug: "stage-structure-raised-platform",
    service_group: "stage-and-platform",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Raised platform and stage structure for ceremonies and performances.",
    description: "Stage structure setup for ceremonies, performances, public functions, and guest-facing focal points.",
    pricing_model: "per_sq_ft",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Stage area",
      quantity_unit: "sq_ft",
      minimum_quantity: 50,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["stage setup", "raised platform", "event stage", "wedding stage"],
  }),
  buildProduct(14, {
    id: "stage-decoration-basic",
    code: "ST-03",
    name: "Stage Decoration (Basic)",
    slug: "stage-decoration-basic",
    service_group: "decoration-and-stage",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Basic stage decor for event presentation and focal styling.",
    description: "Basic stage decor with visual styling, layout support, and event-facing backdrop treatment.",
    pricing_model: "per_setup",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["stage decoration", "stage decor", "basic stage", "event backdrop"],
  }),
  buildProduct(15, {
    id: "flower-decoration-basic",
    code: "DC-01",
    name: "Flower Decoration - Basic",
    slug: "flower-decoration-basic",
    service_group: "decoration-and-stage",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Basic floral decor for stage, entry, and venue styling.",
    description: "Basic flower decoration for entry, stage, mandap, and guest-facing event styling elements.",
    pricing_model: "per_setup",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["flower decoration", "floral decor", "wedding flowers", "event decoration"],
  }),
  buildProduct(16, {
    id: "light-decoration-basic",
    code: "DC-02",
    name: "Light Decoration - Basic",
    slug: "light-decoration-basic",
    service_group: "lighting-and-power",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Basic decorative lighting for ambient event setup.",
    description: "Basic decorative lighting setup for ambience, presentation, and venue enhancement.",
    pricing_model: "per_setup",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["light decoration", "event lighting", "ambient lighting", "decor lights"],
  }),
  buildProduct(17, {
    id: "entry-gate-decoration",
    code: "DC-03",
    name: "Entry Gate Decoration",
    slug: "entry-gate-decoration",
    service_group: "decoration-and-stage",
    category_ids: ["wedding-functions", "family-friends-gatherings", "religious-domestic-ceremonies"],
    short_description: "Decorated entry gate styling for welcome areas.",
    description: "Entry gate decor for first impression styling, guest reception, and thematic venue welcome.",
    pricing_model: "per_unit",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of gates",
      quantity_unit: "gate",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["entry gate decoration", "welcome gate", "event gate decor", "wedding gate"],
  }),
  buildProduct(18, {
    id: "generator-power-backup-rental",
    code: "PW-01",
    name: "Generator / Power Backup - Rental",
    slug: "generator-power-backup-rental",
    service_group: "lighting-and-power",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Generator rental for backup power during functions and events.",
    description: "Power backup rental for event continuity where mains supply is limited or backup support is required.",
    pricing_model: "per_day",
    pricing_notes: ["Fuel is excluded and handled separately by the client per business rules."],
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Generator size",
      quantity_unit: "kva",
      minimum_quantity: 10,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["generator rental", "power backup", "event generator", "wedding generator"],
  }),
  buildProduct(19, {
    id: "fans-coolers",
    code: "PW-03",
    name: "Fans / Coolers",
    slug: "fans-coolers",
    service_group: "lighting-and-power",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Fans and coolers for guest comfort in event venues.",
    description: "Cooling support for guest seating and hosting areas during day events and warm-weather functions.",
    pricing_model: "per_unit_per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of units",
      quantity_unit: "unit",
      minimum_quantity: 1,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["event cooler", "fan rental", "air cooler", "venue cooling"],
  }),
  buildProduct(20, {
    id: "generator-overtime",
    code: "PW-06",
    name: "Generator Overtime",
    slug: "generator-overtime",
    service_group: "lighting-and-power",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Overtime charge for generator usage beyond twelve hours.",
    description: "Additional generator usage beyond the standard twelve-hour day booking window.",
    pricing_model: "per_hour",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Overtime hours",
      quantity_unit: "hour",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: false,
    },
    search_tags: ["generator overtime", "extra generator hours", "power backup overtime"],
  }),
  buildProduct(21, {
    id: "crockery",
    code: "KD-01",
    name: "Crockery",
    slug: "crockery",
    service_group: "kitchen-and-dining-equipment",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Plates, bowls, glasses, and cutlery for guest dining service.",
    description: "Crockery support for plate service, buffet dining, and hosted meal arrangements.",
    pricing_model: "per_plate_set",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of plate sets",
      quantity_unit: "set",
      minimum_quantity: 25,
      duration_required: false,
      manual_review_required: false,
    },
    search_tags: ["crockery rental", "plates bowls cutlery", "event dining", "plate set"],
  }),
  buildProduct(22, {
    id: "cooking-utensils",
    code: "KD-02",
    name: "Cooking Utensils",
    slug: "cooking-utensils",
    service_group: "kitchen-and-dining-equipment",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Cooking utensils and kitchen essentials for bulk event food preparation.",
    description: "Cooking utensil rental for event kitchen operations, large food preparation, and catering support.",
    pricing_model: "per_set_per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of utensil sets",
      quantity_unit: "set",
      minimum_quantity: 1,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: false,
    },
    search_tags: ["cooking utensils", "kitchen rental", "bhagona kadhai", "catering utensils"],
  }),
  buildProduct(23, {
    id: "waiters-servers",
    code: "MP-01",
    name: "Waiters & Servers",
    slug: "waiters-servers",
    service_group: "manpower-and-staff",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Service staff for guest dining and event hospitality support.",
    description: "Waiter and service staff support for dining counters, guest service, and food circulation.",
    pricing_model: "per_person_per_shift",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of staff",
      quantity_unit: "person",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: false,
    },
    search_tags: ["waiter service", "event server", "hospitality staff", "service staff"],
  }),
  buildProduct(24, {
    id: "security-staff-bouncers",
    code: "MP-02",
    name: "Security Staff / Bouncers",
    slug: "security-staff-bouncers",
    service_group: "manpower-and-staff",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Security and crowd control staff for event safety and access handling.",
    description: "Security manpower for guest access, gate handling, and event crowd supervision.",
    pricing_model: "per_person_per_shift",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of staff",
      quantity_unit: "person",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: false,
    },
    search_tags: ["event security", "bouncer service", "security staff", "crowd control"],
  }),
  buildProduct(25, {
    id: "welcome-staff-guest-greeters",
    code: "MP-03",
    name: "Welcome Staff / Guest Greeters",
    slug: "welcome-staff-guest-greeters",
    service_group: "manpower-and-staff",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Welcome team for guest reception and entry assistance.",
    description: "Guest greeting staff for reception desks, entry support, and welcome flow management.",
    pricing_model: "per_person_per_shift",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of staff",
      quantity_unit: "person",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: false,
    },
    search_tags: ["welcome staff", "guest greeters", "reception team", "event welcome"],
  }),
  buildProduct(26, {
    id: "catering-basic-tier",
    code: "CT-01",
    name: "Catering - Basic Tier",
    slug: "catering-basic-tier",
    service_group: "food-and-catering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Basic catering tier for event dining and meal service.",
    description: "Entry-level catering plan for practical meal service and simple hosted events.",
    pricing_model: "per_person",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of guests",
      quantity_unit: "person",
      minimum_quantity: 25,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["basic catering", "event food", "meal service", "wedding catering"],
  }),
  buildProduct(27, {
    id: "catering-standard-tier",
    code: "CT-02",
    name: "Catering - Standard Tier",
    slug: "catering-standard-tier",
    service_group: "food-and-catering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Standard catering tier with improved presentation and service support.",
    description: "Standard catering plan with stronger presentation, organized service, and broader event use.",
    pricing_model: "per_person",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of guests",
      quantity_unit: "person",
      minimum_quantity: 25,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["standard catering", "buffet catering", "event food service", "function catering"],
  }),
  buildProduct(28, {
    id: "catering-premium-tier",
    code: "CT-03",
    name: "Catering - Premium Tier",
    slug: "catering-premium-tier",
    service_group: "food-and-catering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Premium catering tier with elevated menu and service experience.",
    description: "Premium catering plan with upgraded presentation, menu quality, and guest-facing service standards.",
    pricing_model: "per_person",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of guests",
      quantity_unit: "person",
      minimum_quantity: 25,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["premium catering", "luxury catering", "wedding food", "event dining"],
  }),
  buildProduct(29, {
    id: "live-counters-chaat-dessert-stations",
    code: "CT-04",
    name: "Live Counters / Chaat / Dessert Stations",
    slug: "live-counters-chaat-dessert-stations",
    service_group: "food-and-catering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Live food counters and specialty station setups for events.",
    description: "Interactive food station support including live counters, chaat service, and dessert sections.",
    pricing_model: "per_counter",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of counters",
      quantity_unit: "counter",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["live counter", "chaat counter", "dessert station", "food station"],
  }),
  buildProduct(30, {
    id: "welcome-drinks-mocktail-counter",
    code: "CT-05",
    name: "Welcome Drinks / Mocktail Counter",
    slug: "welcome-drinks-mocktail-counter",
    service_group: "food-and-catering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Mocktail and welcome drink counter service for guest arrival.",
    description: "Dedicated welcome drink and mocktail service setup for guest reception and hospitality.",
    pricing_model: "per_counter",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of counters",
      quantity_unit: "counter",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["welcome drink", "mocktail counter", "drinks station", "guest welcome drinks"],
  }),
  buildProduct(31, {
    id: "bartender-service",
    code: "CT-06",
    name: "Bartender Service",
    slug: "bartender-service",
    service_group: "food-and-catering",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional"],
    short_description: "Bartender support for drink service and beverage counters.",
    description: "Bartender staffing for beverage service, mocktail handling, and managed drink counter support.",
    pricing_model: "per_person_per_shift",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of bartenders",
      quantity_unit: "person",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["bartender service", "bar counter", "drink service", "event bartender"],
  }),
  buildProduct(32, {
    id: "flower-decoration-designer-theme",
    code: "DP-01",
    name: "Flower Decoration - Designer / Theme",
    slug: "flower-decoration-designer-theme",
    service_group: "decoration-and-stage",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Premium floral and theme-based event decoration.",
    description: "Designer floral styling for premium events, themed setups, and advanced visual presentation.",
    pricing_model: "per_setup",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["designer flower decoration", "premium floral decor", "theme decor", "wedding flowers"],
  }),
  buildProduct(33, {
    id: "light-decoration-advanced-architectural",
    code: "DP-02",
    name: "Light Decoration - Advanced / Architectural",
    slug: "light-decoration-advanced-architectural",
    service_group: "lighting-and-power",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Advanced lighting design for premium venue presentation.",
    description: "Architectural and premium lighting treatment for highlight zones, stage, facade, and major event moments.",
    pricing_model: "per_setup",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["architectural lighting", "premium event lighting", "designer lighting", "venue lighting"],
  }),
  buildProduct(34, {
    id: "stage-decoration-designer-theme",
    code: "DP-03",
    name: "Stage Decoration - Designer / Theme",
    slug: "stage-decoration-designer-theme",
    service_group: "decoration-and-stage",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Designer stage styling for themed celebrations and events.",
    description: "High-impact stage concept work for themed functions, receptions, and premium public-facing setups.",
    pricing_model: "per_setup",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["designer stage decoration", "premium stage decor", "theme stage", "wedding backdrop"],
  }),
  buildProduct(35, {
    id: "balloon-theme-decoration",
    code: "DP-04",
    name: "Balloon & Theme Decoration",
    slug: "balloon-theme-decoration",
    service_group: "decoration-and-stage",
    category_ids: ["wedding-functions", "family-friends-gatherings"],
    short_description: "Balloon and theme-based decor for parties and celebration functions.",
    description: "Theme-based party styling using balloon work and celebration visuals for social events.",
    pricing_model: "per_setup",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["balloon decoration", "theme decoration", "party decor", "birthday setup"],
  }),
  buildProduct(36, {
    id: "professional-dancers",
    code: "EN-01",
    name: "Professional Dancers",
    slug: "professional-dancers",
    service_group: "music-and-entertainment",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional"],
    short_description: "Dance performances for wedding, party, and stage event entertainment.",
    description: "Professional dance performance support for staged functions, celebrations, and hosted entertainment moments.",
    pricing_model: "per_performance",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of performances",
      quantity_unit: "performance",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["professional dancers", "dance performance", "wedding dancers", "event entertainment"],
  }),
  buildProduct(37, {
    id: "storytellers-kathavachak",
    code: "EN-02",
    name: "Storytellers / Kathavachak",
    slug: "storytellers-kathavachak",
    service_group: "music-and-entertainment",
    category_ids: ["wedding-functions", "religious-domestic-ceremonies"],
    short_description: "Storytelling and kathavachak sessions for traditional and religious gatherings.",
    description: "Traditional storytelling and kathavachak session support for spiritual, ceremonial, and community events.",
    pricing_model: "per_session",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of sessions",
      quantity_unit: "session",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["kathavachak", "storyteller", "religious program", "spiritual event"],
  }),
  buildProduct(38, {
    id: "bhajan-kirtan-party",
    code: "EN-03",
    name: "Bhajan & Kirtan Party",
    slug: "bhajan-kirtan-party",
    service_group: "music-and-entertainment",
    category_ids: ["wedding-functions", "religious-domestic-ceremonies"],
    short_description: "Bhajan and kirtan group performance for spiritual and devotional events.",
    description: "Devotional performance group for bhajan, kirtan, and spiritually focused gatherings.",
    pricing_model: "per_session",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of sessions",
      quantity_unit: "session",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["bhajan party", "kirtan group", "devotional music", "religious event music"],
  }),
  buildProduct(39, {
    id: "event-host-anchor-mc",
    code: "EN-04",
    name: "Event Host / Anchor / MC",
    slug: "event-host-anchor-mc",
    service_group: "music-and-entertainment",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Anchor and host support for event flow, announcements, and stage coordination.",
    description: "Event anchor support for audience flow, announcements, hosting, and public stage continuity.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["event anchor", "mc service", "host for event", "master of ceremonies"],
  }),
  buildProduct(40, {
    id: "dj-sound-setup",
    code: "EN-05",
    name: "DJ & Sound Setup",
    slug: "dj-sound-setup",
    service_group: "music-and-entertainment",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "DJ console and sound setup for event music and audio support.",
    description: "DJ and sound support for celebrations, live hosting, dance segments, and formal program audio needs.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["dj setup", "sound setup", "music system", "event dj", "party dj"],
  }),
  buildProduct(41, {
    id: "live-band-singers",
    code: "EN-06",
    name: "Live Band / Singers",
    slug: "live-band-singers",
    service_group: "music-and-entertainment",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Live music and singer performances for celebrations and programs.",
    description: "Live performance support for music-led events, celebration ambience, and public entertainment segments.",
    pricing_model: "per_performance",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of performances",
      quantity_unit: "performance",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["live band", "event singer", "live music", "wedding singer"],
  }),
  buildProduct(42, {
    id: "event-photography-single-function",
    code: "PH-01",
    name: "Event Photography - Single Function",
    slug: "event-photography-single-function",
    service_group: "photography-and-videography",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Photography coverage for a single event function.",
    description: "Single-function photography service for focused event coverage and memory capture.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["event photography", "photographer", "single function photography", "wedding photographer"],
  }),
  buildProduct(43, {
    id: "event-photography-multi-function-package",
    code: "PH-02",
    name: "Event Photography - Multi-function Package",
    slug: "event-photography-multi-function-package",
    service_group: "photography-and-videography",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Photography package covering multiple event functions.",
    description: "Multi-function photography package for connected celebrations, wedding programs, and event series.",
    pricing_model: "per_package",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["multi function photography", "wedding package photography", "event photo package"],
  }),
  buildProduct(44, {
    id: "videography-cinematography",
    code: "PH-03",
    name: "Videography / Cinematography",
    slug: "videography-cinematography",
    service_group: "photography-and-videography",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Video and cinematic event coverage for functions and celebrations.",
    description: "Videography and cinematic filming support for celebrations, functions, and formal event documentation.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["videography", "cinematography", "event video", "wedding video"],
  }),
  buildProduct(45, {
    id: "pre-wedding-photoshoot",
    code: "PH-04",
    name: "Pre-wedding Photoshoot",
    slug: "pre-wedding-photoshoot",
    service_group: "photography-and-videography",
    category_ids: ["wedding-functions"],
    short_description: "Pre-wedding photoshoot experience for couples before the main celebration.",
    description: "Pre-wedding shoot planning and execution for couples wanting dedicated portrait storytelling before the event.",
    pricing_model: "per_shoot",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["pre wedding shoot", "couple photoshoot", "pre wedding photography", "pre wedding"],
  }),
  buildProduct(46, {
    id: "drone-coverage",
    code: "PH-05",
    name: "Drone Coverage",
    slug: "drone-coverage",
    service_group: "photography-and-videography",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional"],
    short_description: "Drone-based aerial coverage for weddings and large-scale events.",
    description: "Aerial event coverage using drone capture for scale, atmosphere, and highlight moments.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["drone coverage", "aerial videography", "drone shoot", "event drone"],
  }),
  buildProduct(47, {
    id: "album-edited-output",
    code: "PH-06",
    name: "Album / Edited Output",
    slug: "album-edited-output",
    service_group: "photography-and-videography",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Edited albums and final media deliverables from event coverage.",
    description: "Post-production deliverables including edited albums, digital outputs, and final curated event media.",
    pricing_model: "per_deliverable",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of deliverables",
      quantity_unit: "deliverable",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["wedding album", "edited photos", "event album", "photo deliverables"],
  }),
  buildProduct(48, {
    id: "decorated-chauffeur-car",
    code: "BR-01",
    name: "Decorated Chauffeur Car",
    slug: "decorated-chauffeur-car",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Decorated chauffeur-driven car for wedding transportation.",
    description: "Wedding transport support with decorated chauffeur-driven car options for ceremonial movement.",
    pricing_model: "per_vehicle",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of vehicles",
      quantity_unit: "vehicle",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["wedding car", "decorated car", "chauffeur car", "bridal car"],
  }),
  buildProduct(49, {
    id: "vintage-luxury-car",
    code: "BR-02",
    name: "Vintage / Luxury Car",
    slug: "vintage-luxury-car",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Vintage or luxury car option for premium wedding entry and travel.",
    description: "Premium transport option with vintage or luxury cars for wedding procession and arrival moments.",
    pricing_model: "per_vehicle",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of vehicles",
      quantity_unit: "vehicle",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["luxury wedding car", "vintage car", "baraat car", "premium wedding transport"],
  }),
  buildProduct(50, {
    id: "baggi-horse-carriage",
    code: "BR-03",
    name: "Baggi / Horse Carriage",
    slug: "baggi-horse-carriage",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Traditional baggi or carriage for baraat and wedding procession.",
    description: "Traditional carriage support for ceremonial wedding entry and procession styling.",
    pricing_model: "per_unit",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of carriage units",
      quantity_unit: "unit",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["baggi", "horse carriage", "wedding carriage", "baraat carriage"],
  }),
  buildProduct(51, {
    id: "rath-decorated-chariot",
    code: "BR-04",
    name: "Rath / Decorated Chariot",
    slug: "rath-decorated-chariot",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Decorated chariot for ceremonial wedding procession use.",
    description: "Decorated chariot rental for traditional procession and event-led ceremonial entry.",
    pricing_model: "per_unit",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of chariots",
      quantity_unit: "unit",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["rath", "decorated chariot", "wedding chariot", "baraat rath"],
  }),
  buildProduct(52, {
    id: "ghodi-with-attendant",
    code: "BR-05",
    name: "Ghodi with Attendant",
    slug: "ghodi-with-attendant",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Wedding ghodi service with handler for groom procession.",
    description: "Ghodi service with attendant for baraat and traditional groom entry support.",
    pricing_model: "per_unit",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of ghodi bookings",
      quantity_unit: "unit",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["ghodi", "wedding horse", "groom entry", "baraat ghodi"],
  }),
  buildProduct(53, {
    id: "band-baaja-brass-band",
    code: "BR-06",
    name: "Band Baaja / Brass Band",
    slug: "band-baaja-brass-band",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Brass band performance for wedding procession and celebration.",
    description: "Traditional brass band entertainment for baraat movement and wedding celebration atmosphere.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["band baaja", "brass band", "wedding band", "baraat band"],
  }),
  buildProduct(54, {
    id: "dhol-players",
    code: "BR-07",
    name: "Dhol Players",
    slug: "dhol-players",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Dhol performance for baraat and festive music atmosphere.",
    description: "Dhol player support for energetic procession music and celebration movement.",
    pricing_model: "per_person",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: true,
      quantity_label: "Number of dhol players",
      quantity_unit: "person",
      minimum_quantity: 1,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["dhol player", "baraat dhol", "wedding dhol", "dhol service"],
  }),
  buildProduct(55, {
    id: "baraat-photography-videography",
    code: "BR-08",
    name: "Baraat Photography & Videography",
    slug: "baraat-photography-videography",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Dedicated photo and video coverage for baraat procession.",
    description: "Separate baraat-focused capture support for procession movement, entry shots, and celebration energy.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["baraat photography", "baraat videography", "wedding procession shoot", "baraat coverage"],
  }),
  buildProduct(56, {
    id: "baraat-lighting-light-boys",
    code: "BR-09",
    name: "Baraat Lighting / Light Boys",
    slug: "baraat-lighting-light-boys",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Procession lighting support and light-boy service for baraat movement.",
    description: "Lighting support for baraat routes, movement visibility, and ceremonial entry atmosphere.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["baraat lighting", "light boys", "procession lights", "wedding route lighting"],
  }),
  buildProduct(57, {
    id: "flower-shower-petal-cannon",
    code: "BR-10",
    name: "Flower Shower / Petal Cannon",
    slug: "flower-shower-petal-cannon",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Flower shower and petal cannon effects for celebration entries.",
    description: "Celebration effect service for floral entry moments and high-impact welcome visuals.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["flower shower", "petal cannon", "wedding entry effect", "celebration effect"],
  }),
  buildProduct(58, {
    id: "cold-pyro-fireworks",
    code: "BR-11",
    name: "Cold Pyro / Fireworks",
    slug: "cold-pyro-fireworks",
    service_group: "baraat-and-transport",
    category_ids: ["wedding-functions"],
    short_description: "Cold pyro and fireworks effects for special event moments.",
    description: "Special effect service for major event moments, stage highlights, and celebration emphasis.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["cold pyro", "wedding fireworks", "entry effects", "event special effects"],
  }),
  buildProduct(59, {
    id: "community-hall-community-space-coordination",
    code: "VN-01",
    name: "Community Hall / Community Space Coordination",
    slug: "community-hall-community-space-coordination",
    service_group: "venue-coordination",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Venue coordination for community spaces and halls.",
    description: "Community hall and space coordination support to help clients secure workable event locations.",
    pricing_model: "per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["community hall", "venue coordination", "event hall", "hall booking help"],
  }),
  buildProduct(60, {
    id: "open-ground-park-plot-coordination",
    code: "VN-02",
    name: "Open Ground / Park / Plot Coordination",
    slug: "open-ground-park-plot-coordination",
    service_group: "venue-coordination",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Venue coordination for open grounds, parks, and plot-based events.",
    description: "Support for arranging open-ground and plot-based venues where complete event setup is required.",
    pricing_model: "per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["open ground", "park venue", "plot venue", "venue coordination"],
  }),
  buildProduct(61, {
    id: "farmhouse-garden-untied-coordination",
    code: "VN-03",
    name: "Farmhouse / Garden - Untied Coordination",
    slug: "farmhouse-garden-untied-coordination",
    service_group: "venue-coordination",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Venue coordination for untied farmhouses and garden locations.",
    description: "Farmhouse and garden venue coordination where independent setup and event service support is possible.",
    pricing_model: "per_day",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: true,
      duration_label: "Number of days",
      duration_unit: "day",
      minimum_duration: 1,
      manual_review_required: true,
    },
    search_tags: ["farmhouse venue", "garden venue", "farmhouse coordination", "wedding garden"],
  }),
  buildProduct(62, {
    id: "farmhouse-garden-tied-coordination",
    code: "VN-04",
    name: "Farmhouse / Garden - Tied to Another Tent House",
    slug: "farmhouse-garden-tied-coordination",
    service_group: "venue-coordination",
    category_ids: ["wedding-functions"],
    short_description: "On-request venue referral where the site is already tied to another tent house.",
    description: "Referral-based farmhouse or garden venue response for tied sites that require manual review before quoting.",
    pricing_model: "on_request",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["farmhouse referral", "tied venue", "wedding venue on request", "garden referral"],
  }),
  buildProduct(63, {
    id: "banquet-hall-or-vatika",
    code: "VN-06",
    name: "Banquet Hall or Vatika",
    slug: "banquet-hall-or-vatika",
    service_group: "venue-coordination",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional"],
    short_description: "On-request banquet hall or vatika referral support.",
    description: "Referral-style response for banquet hall and vatika venue queries where direct service setup may vary.",
    pricing_model: "on_request",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["banquet hall", "vatika", "wedding hall", "venue referral"],
  }),
  buildProduct(64, {
    id: "event-management-coordination",
    code: "EM-01",
    name: "Event Management & Coordination",
    slug: "event-management-coordination",
    service_group: "event-management",
    category_ids: ["wedding-functions", "family-friends-gatherings", "corporate-institutional", "religious-domestic-ceremonies"],
    short_description: "Event coordination and management support for function execution.",
    description: "End-to-end coordination support to keep event flow, vendors, timing, and execution aligned.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["event management", "event coordination", "function management", "event planning support"],
  }),
  buildProduct(65, {
    id: "wedding-planning-full-service",
    code: "EM-02",
    name: "Wedding Planning (Full-service)",
    slug: "wedding-planning-full-service",
    service_group: "event-management",
    category_ids: ["wedding-functions"],
    short_description: "Full-service wedding planning support from coordination to execution.",
    description: "Comprehensive wedding planning support covering service alignment, event structure, and execution oversight.",
    pricing_model: "per_event",
    quotation_config: {
      quotation_enabled: true,
      quantity_required: false,
      duration_required: false,
      manual_review_required: true,
    },
    search_tags: ["wedding planning", "full service wedding planner", "wedding coordinator", "wedding management"],
  }),
];
